<?php

// @codingStandardsIgnoreFile
/**
 * Ship to multiple address template
 *
 * @var $block \Magento\Multishipping\Block\Checkout\Addresses
 */
?>


<?php if($block->showYearPlateCheckoutForm()): // Check if Cart has a Name Plate Product ?>
<br/>
<div class="checkout_title1">
  <?php echo __('イヤープレート 名入れ') ?>
</div>

<div class="wrapping_table name-plate-form">
  <div class="wrap_row">
    <div class="wrap_subject"><span class="red">＊</span><?php echo __('名入れ') ?></div>
    <div class="wrap_content mark_name">
      <div class="name_field">
        <label for="plate_name_line1"><?php echo __('1行目') ?></label>
        <input type="text" name="plate_name_line1" id="plate-name-line1" maxlength="18">
        <div><?php echo __('半角英数字1行18文字まで、') ?></div>
      </div>
      <div class="name_field">
        <label for="plate_name_line2"><?php echo __('2行目') ?></label>
        <input type="text" name="plate_name_line2" id="plate-name-line2" maxlength="24">
        <div><?php echo __('2行の場合は合計24文字まで。') ?></div>
      </div>
      <div class="red"><?php echo __('イヤープレート名入れの例') ?></div>

      <div><img src="<?php echo $block->getViewFileUrl('images/name_sample_plate.jpg'); ?>" /></div>

      <div class="red"><?php echo __('※名入れにつきましては、ご注文後の内容の変更、及びキャンセルは承っておりません。予めご了承くださいませ。') ?></div>
      <div><?php echo __('※文字色ブルー、ゴシック体、中央揃えになります。') ?></div>
      <div><?php echo __('※使用できる文字は半角英数字 0～9 A～Z a～z 及び アンド &amp; ドット . 等です。スペースも1文字になります。') ?></div>
    </div>
  </div>
</div>

<?php elseif($block->showSubmittedNamePlate()): ?>

<br/>
<div class="checkout_title1">
  <?php echo __('イヤープレート 名入れ') ?>
</div>

<div class="wrapping_table name-plate-submitted-wrapper">
  <div class="wrap_row">
    <div class="wrap_subject"><span class="red">＊</span><?php echo __('名入れ') ?></div>
    <div class="wrap_content mark_name">
      <div class="name_field">
        <label><?php echo __('1行目') ?></label>
        <div><?php echo $block->getNamePlateOne(); ?></div>
      </div>
      <div class="name_field">
        <label><?php echo __('2行目') ?></label>
        <div><?php echo $block->getNamePlateTwo(); ?></div>
      </div>
      <div><span class="red">*</span><?php echo __('名入れにつきましては、ご注文後の内容の変更、及びキャンセルは承っておりません。予めご了承くださいませ。');?></div>
    </div>

  </div>
</div>
<?php endif; ?>

<?php if($block->showTeaCheckoutForm()): // Check if Cart has a Tea Product  ?>
<br/>
<div class="checkout_title1">
  <?php echo __('紅茶 名入れ') ?>
</div>

<div class="wrapping_table tea-form">
  <div class="wrap_row">
    <div class="wrap_subject"><span class="red">＊</span><?php echo __('名入れ') ?></div>
    <div class="wrap_content mark_name">
      <div class="name_field">
        <label for="tea_name_line1"><?php echo __('1行目') ?></label>
        <input type="text" name="tea_name_line1" id="tea-name-line1" maxlength="20">
        <div><?php echo __('半角英数字20文字まで。') ?></div>
      </div>
      <div class="name_field">
        <label for="tea_name_line2"><?php echo __('2行目') ?></label>
        <input type="text" name="tea_name_line2" id="tea-name-line2" maxlength="16">
        <div><?php echo __('半角英数字16文字まで。') ?></div>
      </div>
      <div class="red"><?php echo __('<ラウンドカンティー・名入れ紅茶の名入れの例>') ?></div>

      <div><img src="<?php echo $block->getViewFileUrl('images/name_sample_tea_round.jpg'); ?>" /></div>

      <div><?php echo __('※文字色ブルー、ゴシック体、中央揃えになります。') ?></div>
      <div><?php echo __('※使用できる文字は半角英数字 0～9 A～Z a～z 及び アンド &amp; ドット . 等です。スペースも1文字になります。') ?></div>
      <div class="red"><?php echo __('※名入れにつきましては、ご注文後の内容の変更、及びキャンセルは承っておりません。予めご了承ください。') ?></div>
    </div>
  </div>
</div>

<?php elseif($block->showSubmittedTeaName()): ?>

<br/>
<div class="checkout_title1">
  <?php echo __('紅茶 名入れ') ?>
</div>

<div class="wrapping_table tea-submitted-wrapper">
  <div class="wrap_row">
    <div class="wrap_subject"><span class="red">＊</span><?php echo __('名入れ') ?></div>
    <div class="wrap_content mark_name">
      <div class="name_field">
        <label><?php echo __('1行目') ?></label>
        <div><?php echo $block->getTeaNameOne(); ?></div>
      </div>
      <div class="name_field">
        <label><?php echo __('2行目') ?></label>
        <div><?php echo $block->getTeaNameTwo(); ?></div>
      </div>
      <div><span class="red">*</span><?php echo __('名入れにつきましては、ご注文後の内容の変更、及びキャンセルは承っておりません。予めご了承くださいませ。');?></div>
    </div>

  </div>
</div>
<?php endif; ?>
